### ISSUE TITLE
test do not pass anymore because of a change in the Oni API

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/ldaca-py#5]
`&path=` no longer returned when calling API

https://github.com/Language-Research-Technology/ldaca-py/blob/37dae5b0752cac76b3b1240bf60b1b334f32d1e7/ldaca/ldaca.py#L267

It also errors when creating folders on https://github.com/Language-Research-Technology/ldaca-py/blob/37dae5b0752cac76b3b1240bf60b1b334f32d1e7/ldaca/ldaca.py#L269

Can we make the API backwards compatible or should we change how this is downloading files?

**Comment by alvinsw** [comment]
@ptsefton This is one of the reason why the relative path information must be included separately in it's own property. 

The python script relies on assumption that the URI in `@id` of a File entity follows a certain pattern. I think it is not a good practice as there is no standard that restrict the URI to follow any specific patterns. Sure we can do that in a case of the relative URI, but Oni modifies the relative URI to an absolute URI when it serves the metadata. I strongly argue that the pattern of the absolute URI in `@id` should not be part of the Oni API specification. The user of the API simply **must** not assume that a relative path can be extracted out from the `@id` of a file entity.

Apart from that, the usual representation of a resource (file etc) in REST API is using the paths instead of a query parameter. For example, you normally download a file as `http://example.com/files/subdir/test.pdf` instead of `http://example.com/files?path=subdir/test.pdf`. Current Oni supports both patterns, in a sense that hitting the API with both pattern will give you the file. But you would want the URI in `@id` to be concise.

**Comment by ptsefton** [comment]
@alvinsw the design was discussed extensively and I don't think we can easily change it right even apart from breaking things for clients using it.

There are a couple of facts we have to contend with. 
1. Whatever the API looks like we will need to add parameters for (at least) fetching a particular version of a file like <URL>?v=2
2. Because the underlying OCFL storage my use any kind of http:// URI for a name there is no way to tell where the path to an OCFL object ends and the path begins this is why we settled on using parameters, which may not be considered elegant but it is much less confusing

The path (and version parameters) are part of the API - so clients need to understand their semantics I don't see a problem with that actually - we specify that the path of the file is relative to the object and the client can deal with that. 
We can discuss this for a future version of the API and possible proposals to the RO-Crate group about improvements to handle APIs but ATM I don't think we should break our API.

**Comment by rosanna-smith** [comment]
Alvin reverted the path for API back to the original &path= version and we've confirmed that ldaca-py tests are all working. Added .env override so that any changes to the file are picked up. For reference, the changes we made to the tests based on the new file path are saved on the branch alternate-filepath on my forked version of ldaca-py.
